# Generated by Django 4.0 on 2022-01-10 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('classs', models.IntegerField()),
                ('rollnumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='clasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=400)),
                ('clas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Student.studentmodel')),
            ],
        ),
    ]
