# Generated by Django 4.0 on 2022-01-11 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathername', models.CharField(max_length=200)),
                ('mothername', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('emailid', models.EmailField(max_length=254)),
                ('contactnumber', models.IntegerField(max_length=200)),
                ('image', models.URLField()),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Student.studentmodel')),
            ],
        ),
    ]
