# Generated by Django 4.0 on 2022-01-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_profilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='contactnumber',
            field=models.IntegerField(),
        ),
    ]
