# Generated by Django 4.0 on 2022-01-27 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doc', models.ImageField(upload_to='')),
                ('Doc_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.studentmodel')),
            ],
        ),
    ]
