# Generated by Django 4.0 on 2022-01-27 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pic', models.URLField()),
                ('galerry_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.studentmodel')),
            ],
        ),
    ]
