# Generated by Django 4.0 on 2022-01-31 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='image',
            field=models.ImageField(blank=True, default='bear-grylls.jpg', null=True, upload_to=''),
        ),
    ]
