# Generated by Django 4.0 on 2022-01-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_studentmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='gender',
            field=models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
