# Generated by Django 4.0 on 2022-02-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_studentmodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.ManyToManyField(to='Student.StudentModel')),
            ],
        ),
    ]
