# Generated by Django 4.0 on 2022-02-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0009_alter_studentmodel_gender_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='Like',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
