# Generated by Django 4.0 on 2022-02-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0010_likes_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dislike', models.BooleanField()),
                ('dislike', models.ManyToManyField(to='Student.StudentModel')),
            ],
        ),
    ]
